//
//  ViewController.swift
//  UserDefaultsPractice
//
//  Created by Bumhan Yu on 2/18/15.
//  Copyright (c) 2015 Bumhan Yu. All rights reserved.
//

import UIKit

class ViewController: UIViewController {

    @IBOutlet weak var backgroundSwitch: UISwitch!
    
    @IBOutlet weak var switchLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.

        self.backgroundSwitch.addTarget(self, action: "didChangeSwitch", forControlEvents: UIControlEvents.ValueChanged)
            // ValueChanged is a general call for changing values
            // "self" is an instance of a class. NOT a class name here.
        
        self.backgroundSwitch.on = NSUserDefaults.standardUserDefaults().boolForKey("switchIsOn")
        
        didChangeSwitch()
            // manually initiate the function to make sure font change takes effect. "addTarget" method doesn't get triggered when the value is manually added like this.
        
//        let array = NSArray(contentsOfFile: "sample.plist")
            // you need to provide full path to the file
        
        if let resourcePath = NSBundle.mainBundle().pathForResource("sample", ofType: "plist") {
                // NSBundle method works only with preloaded file with the app. Files dynamically generated by user cannot be accessed by this.
            
            var array = NSArray(contentsOfFile: resourcePath)
            println(array)
            
            array?.writeToFile(resourcePath, atomically: true)
        }
    }
    
    func didChangeSwitch() {
    //    println(self.backgroundSwitch.on)
            // see if the switch is on: true for on, false for off
        
        if self.backgroundSwitch.on {
            self.switchLabel.font = UIFont.systemFontOfSize(30)
                // bigger font size when switch is on
        } else {
            self.switchLabel.font = UIFont.systemFontOfSize(10)
                // smaller font size when switch is off
        }
        NSUserDefaults.standardUserDefaults().setBool(self.backgroundSwitch.on, forKey: "switchIsOn")
                // store boolean data to UserDefaults

        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}

